### PR TITLE
Module/proj mgmt

### LINKED ISSUE #45: module: int project management

### PR DESCRIPTION
**Pull request by richpauloo**
Project management module that closes #45.

I also added some css for code block styling, and spent about an hour trying to figure out how to wrap text with no success. Please see the html doc for this lesson to see what I mean. There's a super long url that I can't figure out how to wrap. I tried modifying the `pre` and `sourceCode` tags with all manner of css to no avail. If there's any way you can finagle that, I would really appreciate it, but don't worry about it too much. You can still copy and paste even though the url runs way off the page.

### CODE REVIEW

**Comment by ryanpeek** [comment]
I'll take a look at this later this afternoon. for the wrapping issue, I've run into this for formatting Rmd for my disseration, here are a few options that we can try...I'll see if I can add a worked example later, but I think this issue has been solved via Yihui (as usual!) and the [formatR package](https://yihui.org/formatr/). See here:

- https://bookdown.org/yihui/rmarkdown-cookbook/opts-tidy.html
- install the formatR and load in knitr options at beginning of doc
- and in a given code chunk, try: `{r, tidy=TRUE, tidy.opts=list(width.cutoff=60)}`

**Comment by richpauloo** [comment]
Yihui. What a legend.

I just gave this a try, both in the chunk options, as well as globally via `knitr::opts_chunk$set()` to no success. Perhaps you'll see something I don't. =\

**Comment by ryanpeek** [comment]
for the "Review" box CSS, we need to make the line spacing a little bigger. The text feels a bit crunched vertically, so maybe make line spacing a touch wider.

**Comment by richpauloo** [comment]
Just fixed that with a quick CSS.

**Comment by ryanpeek** [comment]
Ok! Take a look at my edits. I think this looks good but needs a few little definitions/simplifications..even though it's intermediate, it's good to be clear for folks that may not know the jargon.

Also, will we have covered purrr::walk by this point? If not, since it's used to load packages/cowsay, may want to give a little aside or footnote to another lesson for folks that may not have seen this before.

Good work! 👍

**Review by ryanpeek — APPROVED** [review]

**Comment by richpauloo** [comment]
Great additions and review! I changed some things you pointed out, explained things that needed more explaining, and really like how you broke up the url with `glue`. Thanks!

I'll leave this PR open for another day or so in case you want to view the changes before I merge.

**Comment by ryanpeek** [comment]
Great, I think it looks good, but if you can either in the aside box or in the body of the text, explain specifically what a "***predictable development environment***" is (or link to something that does the job) that would be great. I think we need to define that part a bit more. I initially put the aside box in as a placeholder for some content, but then didn't tell you that. 😄 

Good work!

**Comment by richpauloo** [comment]
Okay, I snuck in some refactors to the intro branch on this PR. Try reknitting some of the intro modules, scroll to the bottom, and use the navigation links. 

An unintended side-effect of importing the bottstrap css is that all `code` backticked words are now formatted in pink, but I kind of like how it makes these stand out. We can change that color of course, but I thought I'd leave it for now to see what you think.

**Comment by ryanpeek** [comment]
this looks great, and I think the pink "pops" nicely...we can change if we want later if we feel it's distracting. But for now, merge it and deploy! This looks nice, thanks for adding the buttons and spacing.

**Pull request merged**
