### PR TITLE
automation module

### PR DESCRIPTION
**Pull request by richpauloo**

### CODE REVIEW

**Comment by richpauloo** [comment]
Sorry there are straggling html and search.json files in this messy PR. They're left over from before our last conversation. 

Also, to knit, you'll need to unzip `/intermediate/data/pgwl/measurements.zip`, but be sure not to commit the unzipped .csv it back to the repo because it's too big.

**Comment by ryanpeek** [comment]
So first pass through I made a few edits but ran out of steam...I'll try to finish up tomorrow. My gut take is this is a really dense lesson (lots of good stuff inside!) but this is like a whole day in one lesson. It needs some serious trimming, or we need to think about how this would be taught...in my initial run through, I'm not sure how long it would take to teach this. I tried to start breaking things into smaller chunks/sections, which may help identify the key pieces of each section (so you can decide what would make sense to keep/drop/trim).

 So, my suggestions are as follows (and happy to chat more on the phone/zoom about this):

- What are the key tasks/skills that you want to teach in this lesson? 
- What is the minimum set of text/code/wrangling that you can do and still get the lesson across?
- I like the story, but I feel like the lede is buried a bit...I think it's hard to try and cover the reproducible workflows + iteration + automation all in one. How about trying to integrate the "how to write helpful functions" section a bit earlier? I feel like that's the meat of the lesson really, and if we could get to that bit sooner (or splice in the groundwater setup stuff earlier) this may work more fluidly.

Hopefully this feedback comes across ok, it's a great bit of content, it's just a lot, particularly if we are trying to teach recent learners...this feels like more like an advanced course lesson (but it's so topical which is great!). We could think about weighting a few of these lessons as "more advanced" and just make some prerequisites clear at the beginning of the lesson.

More soon!

**Review by ryanpeek — CHANGES_REQUESTED** [review]
See my comments

**Comment by richpauloo** [comment]
Hey Ryan, thanks for the feedback. I needed to hear that. 

I struggled with this lesson, and it can probably use a major refactor at a later date. Your changes in framing, especially, "how to write helpful functions" are helpful.

This lesson is actually not that long, but it *feels* super long because it starts with a non-functional workflow, than converts each step into a function, and each function has a bunch of "user friendliness" built in to check for correct object types, inputs, etc. I agree that if read top to bottom during a class, it would be unwieldy and unrealistic to get through. 

One way to approach teaching core content in the lesson is to acknowledge that it's more of an advanced topic, and keep it high level, and make it more of a show-and-tell with minimal coding on their part (only the essential bits):

- overview of reproducibility, starting with functions and don't repeat yourself (Figure 1 is the core message)
- we encourage students to dive into the nitty gritty of each function at a later time, but for now, just absorb the structure of organizing code in this way and the automation potential it has once organized like so
- we skip all functional stuff, straight to the wrapper script, 00_control.R, and run it line by line with students, then from source() to demonstrate output. we highlight the functions folder
- we call `rscript 00_control.R` from the cmd line and talk about how we can configure a task scheduler to this

That will allow us to stay at a high level with this lesson, but still give the students a much more in-depth lesson if they want to get into the weeds.

Thoughts?

**Pull request merged**
